[project]
name = "bytewax"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: System :: Networking",
    "Topic :: System :: Distributed Computing",
]
dependencies = [
    "jsonpickle>=3",
    "typing_extensions>=4",
    "prometheus-client>=0.18"
]

extras = [
    "kafka",
]

[project.optional-dependencies]
kafka = [
    "requests>=2.0",
    "fastavro>=1.8",
    "confluent-kafka>=2.0.2",
]

[project.urls]
"Source Code" = "https://github.com/bytewax/bytewax"
Issues = "https://github.com/bytewax/bytewax/issues"
Documentation = "https://docs.bytewax.io/"
Changelog = "https://github.com/bytewax/bytewax/blob/main/CHANGELOG.md"

[metadata]
long_description = "file: README.md"
long_description_content_type = "text/markdown"

[build-system]
requires = ["maturin"]
build-backend = "maturin"

[tool.hatch]

[tool.hatch.env]
requires = [
    "hatch-pip-compile",
]

[tool.maturin]
module-name = "bytewax._bytewax"
python-source = "pysrc"

# TODO: Get stubgen automatically built.
# https://hatch.pypa.io/latest/plugins/build-hook/custom/
# [tool.hatch.build.hooks.custom]
# path = "stubgen.py"

[tool.hatch.env.default]
type = "pip-compile"
pip-compile-hashes = true

[tool.hatch.envs.test]
dependencies = [
    "pytest",
    "pytest-benchmark",
    "pytest-codspeed",
    "sybil",
]
features = [
    "kafka",
]

[[tool.hatch.envs.test.matrix]]
python = [
    "3.8",
    "3.9",
    "3.10",
    "3.11",
    "3.12",
]

[tool.hatch.envs.test.scripts]
tests = "pytest --benchmark-skip {args}"
benchmarks = "pytest --benchmark-only {args}"

[tool.pytest.ini_options]
addopts = "-v -p no:doctest"
testpaths = [
    "docs",
    "pytests",
    "pysrc",
    "README.md",
]

[tool.hatch.envs.lint]
skip-install = true
dependencies = [
    "mypy",
    "ruff",
    "vermin",
]

[tool.hatch.envs.lint.scripts]
check = [
    "ruff check",
    "mypy pysrc/",
    "vermin --no-tips --eval-annotations --no-parse-comments --violations -t=3.8- pysrc/",
]

[tool.mypy]
mypy_path = "pysrc"

[tool.ruff.lint]
select = [
    "A",
    "B",
    "D",
    "DTZ",
    "E",
    "EM",
    "F",
    "I",
    "PL",
    "W",
]
ignore = [
    "D105",
    "E731",
    "PLR",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.per-file-ignores]
"examples/*.py" = ["D"]
"pytests/test_flows/*.py" = ["D"]
"test_*.py" = ["D"]
# Because `test_encoder` has huge literals in it.
"pytests/test_encoder.py" = ["E501"]

[tool.hatch.envs.docs]
skip-install = true
python = "3.10"  # To match .readthedocs.yml.
dependencies = [
    "myst-parser",
    "pydata-sphinx-theme",
    "sphinx",
    "sphinx-autodoc2",
    "sphinx-favicon",
    "sphinxcontrib-mermaid",
]

[tool.hatch.envs.docs.scripts]
autobuild = "sphinx-autobuild -E docs docs/_build"
build = "sphinx-build -b html -E docs docs/_build"
tests = "sphinx-build -b doctest -E docs docs/_build"
