name: benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install --user uv
      - uses: extractions/setup-just@v2
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -o dist -i python-3.12
          sccache: true
      - name: Prep test venv
        shell: bash
        run: |
          mkdir -p venvs/
          uv venv venvs/test-py3.12/
          . venvs/test-py3.12/bin/activate
          WHEEL_FILE=$(ls ./dist/*.whl)
          uv pip sync --strict requirements/test-py3.12.txt
          uv pip install -v --no-deps $WHEEL_FILE
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: |
            . test-py3.12/bin/activate
            just test-benchmark
