name: benchmarks

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Hatch
        run: pip install hatch
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release -o dist -i python-3.12
          sccache: true
      - name: Prep test venv
        shell: bash
        env:
          PIP_COMPILE_DISABLE: 1
        # First `PIP_COMPILE_DISABLE` ensures that we have a fully
        # locked venv. Then we do something gross which that Hatch
        # automatically installs the local dev version of Bytewax, so
        # we manually uninstall it from the venv and re-install the
        # final wheel.
        run: |
          hatch -vv env create
          hatch env run -- pip uninstall -vy bytewax
          WHEEL_FILE=$(ls ./dist/*.whl)
          hatch env run -- pip install -v --no-deps $WHEEL_FILE
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v2
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: hatch env run py-benchmarks
